apiVersion: v1

kind: Service

# DNS name (postgres-service.default.svc.cluster.local)
metadata:
  name: postgres-service

spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      # Service port
      port: 5432
      # Container port
      targetPort: 5432
  # Internal only
  type: ClusterIP
